### ISSUE TITLE
V2无限loading

### ISSUE THREAD

**Issue by kid101x** [manakanemu/ExHentaiReader#17]
最近发现去年有v2版本，想体验下，结果发现Alook中无限loading。
似乎是gif元素卡住了？
看控制台报错是：
```
Reader_V2.js:178  Uncaught TypeError: Cannot read properties of null (reading '1')
    at ImageMeta.<anonymous> (Reader_V2.js:178:67)
    at GET.xhr.onload (Reader_V2.js:49:20)
```
跳转对应内容为：
```
    callImageUrl() {
        this.state = 3;
        GET.call(this, this.imagePageUrl, function (d) {
            var imgUrl = d.match(/<img id=\"img\" src=\"(.+?)\"/i)[1]; //就这行报错了
            var nl = d.match(/onclick=\"return nl\(\'(.+?)\'\)\"/i)[1];
            this.url = imgUrl;
            this.nl = nl;
            this.imageWidget.updateImageDOM()
        }, "text")
    }
```

**Comment by invinciberry** [comment]
今天第一次遇到这个问题，有办法解决么🫥
